Update for CUBE change to compute_resources

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -136,41 +136,34 @@ runs:
         fi
 
         if [ -z "${{ inputs.compute_resources }}" ]; then
-          echo "::error ::chris_admin_auth is required"
+          echo "::error ::compute_resources is required"
           exit 1
         fi
 
         set +e  # let us handle error, instead of stopping silently
 
-        # split csv into array
-        IFS=',' read -ra compute_resources <<< "${{ inputs.compute_resources }}"
+        res="$(
+          curl -s --show-error \
+            -u "${{ inputs.chris_admin_auth }}" \
+            "${{ inputs.chris_admin_url }}" \
+            -H 'Accept: application/json' \
+            -H 'Content-Type: application/json' \
+            --data '{"compute_names": "${{ inputs.compute_resources }}", "plugin_store_url": "${{ steps.upload.outputs.href }}"}'
+        )"
 
-        for cr in "${compute_resources[@]}"; do
-          >&2 echo "${{ steps.upload.outputs.href }} --> $cr"
+        success=$?
+        echo "::debug::$res"
+        if [ "$success" = "0" ] \
+            && url="$(jq -r '.url' <<< "$res")" \
+            && [ "$url" = "null" ]; then
+          success=1
+        fi
 
-          res="$(
-            curl -s --show-error \
-              -u "${{ inputs.chris_admin_auth }}" \
-              "${{ inputs.chris_admin_url }}" \
-              -H 'Accept: application/json' \
-              -H 'Content-Type: application/json' \
-              --data '{"compute_name": "'$cr'", "plugin_store_url": "${{ steps.upload.outputs.href }}"}'
-          )"
-
-          success=$?
-          echo "::debug::$res"
-          if [ "$success" = "0" ] \
-              && url="$(jq -r '.url' <<< "$res")" \
-              && [ "$url" = "null" ]; then
-            success=1
-          fi
-
-          if [ "$success" != "0" ]; then
-            echo "::error ::Failed to register plugin to CUBE."
-            echo "::error ::response: $res"
-            exit $success
-          fi
-        done
+        if [ "$success" != "0" ]; then
+          echo "::error ::Failed to register plugin to CUBE."
+          echo "::error ::response: $res"
+          exit $success
+        fi
 
         echo "::set-output name=url::$url"
 
